local_costmap:
   global_frame: /world2
#/world2
   robot_base_frame: base_link1
#/base_link1
   update_frequency: 6.0
   publish_frequency: 3.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
